<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="3" total="4" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-31T17:12:12 IST" name="Default suite" finished-at="2024-12-31T17:12:48 IST" duration-ms="36454">
    <groups>
    </groups>
    <test started-at="2024-12-31T17:12:12 IST" name="Default test" finished-at="2024-12-31T17:12:48 IST" duration-ms="36454">
      <class name="NegativeTestCases.TC_AlertPage">
        <test-method is-config="true" signature="createObjects()[pri:0, instance:NegativeTestCases.TC_AlertPage@37afeb11]" started-at="2024-12-31T17:12:12 IST" name="createObjects" finished-at="2024-12-31T17:12:12 IST" duration-ms="434" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createObjects -->
        <test-method is-config="true" signature="invokeBrowser()[pri:0, instance:NegativeTestCases.TC_AlertPage@37afeb11]" started-at="2024-12-31T17:12:12 IST" name="invokeBrowser" finished-at="2024-12-31T17:12:30 IST" duration-ms="18017" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invokeBrowser -->
        <test-method signature="erifyValidationMessageAppearsWhenSubmittingWithoutInput()[pri:4, instance:NegativeTestCases.TC_AlertPage@37afeb11]" started-at="2024-12-31T17:12:30 IST" name="erifyValidationMessageAppearsWhenSubmittingWithoutInput" finished-at="2024-12-31T17:12:47 IST" duration-ms="16349" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at PageObjects.AlertPage.verifyValidationAppearForSearchBox(AlertPage.java:256)
at NegativeTestCases.TC_AlertPage.erifyValidationMessageAppearsWhenSubmittingWithoutInput(TC_AlertPage.java:79)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- erifyValidationMessageAppearsWhenSubmittingWithoutInput -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:NegativeTestCases.TC_AlertPage@37afeb11]" started-at="2024-12-31T17:12:47 IST" name="tearDown" finished-at="2024-12-31T17:12:48 IST" duration-ms="1379" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- NegativeTestCases.TC_AlertPage -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
